# Metadata
NAME = 'FitLater'
VERSION = '0.1.0'

# Correlation 
CORRELATION_THRESHOLD = 0.6

# Outliers
OUTLIER_THRESHOLD = 0.01

# CLI
MISSING_THRESHOLD = 5.0
SKEW_THRESHOLD = 1.0
HIGH_CARDINALITY_THRESHOLD = 50
DUPLICATE_THRESHOLD = 1